### ISSUE TITLE
Understanding the directory option

### ISSUE THREAD

**Issue by mhaamann** [gmarty/xgettext#55]
In version 2.6.1 the following command worked just fine. It found all the files inside the folder templates and its subfolders. Now we are just getting 'no input file given'. What are we doing wrong.

I see that version 3 introduced breaking changes, but I am not sure how to use the new options.

Command
```
xgettext-template --force-po --directory templates -L Handlebars --output i18n/handlebars.pot
```
Output:
```
xgettext-template: no input file given

Try 'xgettext-template --help' for more information.
```

**Comment by smhg** [comment]
Behavior of `--directory|-D` indeed changed.
The short answer: `xgettext-template` now requires you to list the files it needs to parse yourself.
The solution is rather straightforward: pipe the result of a file search. An example can be found in [this comment](https://github.com/gmarty/xgettext/issues/49#issuecomment-231305452).

The full answer: the goal of this project is to make `xgettext-template` a drop-in replacement for the "native" `xgettext`. Since version 3 all implemented parameters and flags (should) match.
The `--directory|-D` parameter now only changes the root directory in which the listed files are then looked up.

If you work with Poedit, Poedit does this for you. If you call `xgettext-template` in any other way, you have to send it the files it needs to parse (e.g. with `find`).

**Comment by mhaamann** [comment]
Thanks!
